### ISSUE TITLE
pinn

### ISSUE THREAD

**Issue by ByteBardy** [Sysuzqs/PDENNEval#3]
您好，关于pinn中，对于Pl，Ps，Ph的py文件，这里：from GenerateData import *  是什么呢？

**Comment by 12138xs** [comment]
您好！from GenerateData import * 这一行代码用于导入 GenerateData.py 文件中的所有函数和类。GenerateData.py 包含了一些用于在立方体或球体内生成样本点的函数，该文件已经补充到代码仓中。感谢您的关注！如果您还有其他问题，请随时问我。
